# Generated by Django 5.2.15 on 2026-07-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
