# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_api', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(
                fields=('voter', 'election'),
                name='one_vote_per_voter_per_election',
            ),
        ),
    ]
