# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_api', '0003_vote_one_vote_per_voter_per_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_vote_per_voter_per_election',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'position'), name='one_vote_per_voter_per_election_position'),
        ),
    ]
