# Generated by Django 5.2.15 on 2026-07-16 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_api', '0005_election_results_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_vote_per_voter_per_election_position',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'candidate'), name='one_vote_per_candidate'),
        ),
    ]
