# Generated by Django 5.2.15 on 2026-07-16 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_api', '0007_remove_vote_one_vote_per_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_vote_per_voter_per_election_position',
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'position'), name='one_vote_per_voter_per_election_position'),
        ),
    ]
